### ISSUE TITLE
Lint the code with Flake8

### ISSUE THREAD

**Issue by Jangsoodlor** [JaofourthsOhappy/ku-polls#37]
There are a lot of errors from flake8. Please make sure that you install `flake8-docstrings` and re-lint your code.

**Comment by JaofourthsOhappy** [comment]
A few exceptions to flake8 code analysis are allowed such as:
ignore files autogenerated by Django (migrations, mysite files)
lines in models can be up to 100 chars long
ignore minor issues like missing docstring in __init__.py files
