### ISSUE TITLE
(Suggestion) Add "Other" option in polls

### ISSUE THREAD

**Issue by Jangsoodlor** [JaofourthsOhappy/ku-polls#41]
the current poll's options may not align with everyone's views. For example, some people may think that Chocolate Frappe is the best menu at Starbucks. Or Wat Phra Sri Mahathat Bang Khen is the most beautiful temple in Bangkok. Adding the "Other" option is the easiest way to solve that in my opinion.

**Comment by JaofourthsOhappy** [comment]
fix in #38
